### ISSUE TITLE
Not working on Android 5.1.1

### ISSUE THREAD

**Issue by mihnagy** [starryalley/AmbitSync#3]
On my Sony Xperia M2, using Android 5.1.1, it doesn't work: I connect my Ambit 2 watch while the app is running and nothing happens. It doesn't seem to recognize the watch.

**Comment by starryalley** [comment]
Hi @mihnagy , could you make sure the following:

Is the same OTG cable you used working with other USB devices? For example, a flash drive on your phone?

If it always work, then something is wrong with this combination (phone, android version running on it, and the ambit device). Unfortunately I may not be able to help since I don't have the phone.

If it doesn't, it may mean the cable or any connecting parts is bad, or the phone doesn't support USB host mode (unlikely I guess.). 

However, I got a Google Pixel XL 2 and the ambit sometimes doesn't get detected as well. I have to detach and re-attach the OTG cables for 1 or 2 times before I can use it. But on a Samsung S8 it works flawlessly every time with the same cable. I don't know why as well.

**Comment by mihnagy** [comment]
I tried connecting and disconnecting it multiple times and eventualy it worked. 
Thanks for the quick response and great job making this app!
